export const PLANT_TOOLS: Record<string, { name: string; icon: string }> = {
    eclipse_hoe: { name: "Eclipse Hoe", icon: "" },
    fungi_cutter: { name: "Fungi Cutter", icon: "" },
    wild_rose_hoe: { name: "Wild Rose Hoe", icon: "" },
    turing_sugar_cane_hoe: { name: "Turing Sugar Cane Hoe", icon: "" },
    gauss_carrot_hoe: { name: "Gauss Carrot Hoe", icon: "" },
    pumpkin_dicer: { name: "Pumpkin Dicer", icon: "" },
    melon_dicer: { name: "Melon Dicer", icon: "" },
    cocoa_chopper: { name: "Cocoa Chopper", icon: "" },
    newton_nether_wart_hoe: { name: "Newton Nether Wart Hoe", icon: "" },
    pythagorean_potato_hoe: { name: "Pythagorean Potato Hoe", icon: "" },
    pickaxe_drill: { name: "Pickaxe/Drill", icon: "⛏" },
    any_tool: { name: "Any Tool", icon: "" },
};

export const RECOMMENDED_TOOLS: Record<string, keyof typeof PLANT_TOOLS> = {
    ashwreath: "newton_nether_wart_hoe",
    choconut: "cocoa_chopper",
    dustgrain: "gauss_carrot_hoe",
    gloomgourd: "pumpkin_dicer",
    lonelily: "pumpkin_dicer",
    scourrroot: "gauss_carrot_hoe",
    shadevine: "turing_sugar_cane_hoe",
    veilshroom: "fungi_cutter",
    witherbloom: "wild_rose_hoe",
    chocoberry: "melon_dicer",
    cindershade: "newton_nether_wart_hoe",
    coalroot: "gauss_carrot_hoe",
    creambloom: "cocoa_chopper",
    duskbloom: "eclipse_hoe",
    thornshade: "fungi_cutter",
    blastberry: "newton_nether_wart_hoe",
    cheesebite: "fungi_cutter",
    chloronite: "pickaxe_drill",
    do_not_eat_shroom: "fungi_cutter",
    fleshtrap: "pumpkin_dicer",
    magic_jellybean: "eclipse_hoe",
    noctilume: "wild_rose_hoe",
    snoozling: "eclipse_hoe",
    soggybud: "melon_dicer",
    chorus_fruit: "turing_sugar_cane_hoe",
    plantboy_advance: "eclipse_hoe",
    puffercloud: "fungi_cutter",
    shellfruit: "melon_dicer",
    startlevine: "turing_sugar_cane_hoe",
    stoplight_petal: "wild_rose_hoe",
    thunderling: "wild_rose_hoe",
    turtlellini: "any_tool",
    zombud: "pumpkin_dicer",
    all_in_aloe: "eclipse_hoe",
    devourer: "fungi_cutter",
    glasscorn: "pythagorean_potato_hoe",
    phantomleaf: "gauss_carrot_hoe",
    timestalk: "turing_sugar_cane_hoe",
    godseed: "eclipse_hoe",
};